export const SET_USER = "SET_USER";
export const SET_MODAL = "SET_MODAL";
export const SET_QUIZ_ROOMS_LIST = "SET_QUIZ_ROOMS_LIST";
export const SET_QUIZ_CURRENT_SESSION = "SET_QUIZ_CURRENT_SESSION";
